import type { ThemeDefinition } from './types'

const theme: ThemeDefinition = {
  id: 'day4-sand',
  label: {
    ko: '샌드 코랄',
    en: 'Sand Coral',
  },
  tokens: {
    'bg-page': '#f8f1e8',
    'text-primary': '#2a1f17',
    'text-muted': '#5f4a3e',
    'text-subtle': '#7a6356',
    'text-strong': '#3a2a20',
    'surface': '#fffaf4',
    'panel-bg': '#fff7ef',
    'border-panel': '#e8d7c7',
    'border-soft': '#eadccc',
    'border-card': '#eddccc',
    'input-border': '#d8bea8',
    'primary': '#c85f3f',
    'primary-contrast': '#fffaf4',
    'secondary-text': '#a65036',
    'secondary-border': '#d7b59c',
    'success-bg': '#ecf8e7',
    'success-text': '#2f7a41',
    'success-border': '#b9e1c3',
    'warning-bg': '#ffefe7',
    'warning-text': '#b24a34',
    'warning-border': '#f3c2b6',
    'error-text': '#b42318',
    'hover-bg': '#fff0e6',
    'hover-border': '#efcdb8',
    'guide-head-bg': '#fbefe3',
    'guide-copy-border': '#e2c6b1',
    'guide-copy-text': '#533b2d',
    'guide-copy-hover': '#fff3eb',
    'chart-grid': '#f3e6db',
    'chart-axis': '#bf9f8b',
    'chart-target': '#ce4d47',
    'chart-trend': '#2f8a58',
    'chart-record': '#b85c3d',
    'profile-bg': '#b85c3d',
    'profile-border': '#b85c3d',
    'shadow-elev': '0 8px 20px rgba(50, 32, 19, 0.14)',
  },
}

export default theme
