import type { ThemeDefinition } from './types'

const theme: ThemeDefinition = {
  id: 'day4-light',
  label: {
    ko: '라이트 블루',
    en: 'Light Blue',
  },
  tokens: {
    'bg-page': '#eef3fb',
    'text-primary': '#13203a',
    'text-muted': '#44506a',
    'text-subtle': '#5f6c89',
    'text-strong': '#24314f',
    'surface': '#ffffff',
    'panel-bg': '#f8fbff',
    'border-panel': '#d8dde8',
    'border-soft': '#dbe2f1',
    'border-card': '#e2e6ef',
    'input-border': '#c4ccdb',
    'primary': '#175cd3',
    'primary-contrast': '#ffffff',
    'secondary-text': '#175cd3',
    'secondary-border': '#a9b8d4',
    'success-bg': '#e8f7ed',
    'success-text': '#1f7a3d',
    'success-border': '#b8e4c4',
    'warning-bg': '#fdf0ef',
    'warning-text': '#b9382f',
    'warning-border': '#f1c3be',
    'error-text': '#b42318',
    'hover-bg': '#f2f6ff',
    'hover-border': '#d6def1',
    'guide-head-bg': '#eef2fb',
    'guide-copy-border': '#cfd8ec',
    'guide-copy-text': '#2b3a5f',
    'guide-copy-hover': '#f1f5ff',
    'chart-grid': '#edf1f7',
    'chart-axis': '#9eabc6',
    'chart-target': '#d64545',
    'chart-trend': '#2f9e44',
    'chart-record': '#175cd3',
    'profile-bg': '#175cd3',
    'profile-border': '#175cd3',
    'shadow-elev': '0 8px 20px rgba(15, 23, 38, 0.12)',
  },
}

export default theme
