create table if not exists public.users (
  id bigint generated by default as identity primary key,
  google_sub text not null unique,
  email text,
  name text,
  picture_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.goals (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  name text not null,
  target_date text not null,
  target_level double precision not null,
  unit text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.goal_records (
  id bigint generated by default as identity primary key,
  goal_id bigint not null references public.goals(id) on delete cascade,
  date text not null,
  level double precision not null,
  message text,
  created_at timestamptz not null default now()
);

create table if not exists public.user_settings (
  user_id bigint not null references public.users(id) on delete cascade,
  key text not null,
  value text not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, key)
);

create index if not exists idx_goals_user_id on public.goals(user_id);
create index if not exists idx_goal_records_goal_id on public.goal_records(goal_id);

alter table public.users enable row level security;
alter table public.goals enable row level security;
alter table public.goal_records enable row level security;
alter table public.user_settings enable row level security;
